### ISSUE TITLE
Dragonfly Fighters trigger a dump

### ISSUE THREAD

**Issue by kabivel** [kabivel/Sins-of-Empires#1]
With the 0.5 and the 0.4 versions, every time I spawn Dragonfly Fighters for the Caldari Chimera carrier, my game crashes. I'm checking 0.3 now

**Comment by Joeyxxx** [comment]
I haven't experienced any mini dumps in the latest version. Is this still an issue or can we close this?

**Comment by vader111** [comment]
yeah this is really old before i fixed it so it can be closed
