### ISSUE TITLE
FAX issues

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#125]
I'm not sure exactly what is wrong with FAX's but:

- They don't automatically use Triage
- They rarely remote repair
- They do however remote capacitor
- They self-rep even if they are full hull/shield

**Comment by kabivel** [comment]
They self-rep even if they are full hull/shield - fixed with autocast disabled

**Comment by kabivel** [comment]
Changed AI autoactivation to in combat, before was OnlyWhenAttackTargetIsInFiringSolutionAndHasAttackOrder

**Comment by kabivel** [comment]
remote repair is hardcoded stuff, is set to use but the ai dont use. halved the antimatter cost to see if works.
