### ISSUE TITLE
HIC bubble 

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#128]
Could we update the HIC bubble to look like the DIC bubbles?

Currently you can't see your fleet inside of it.

**Comment by TempusLupus** [comment]
Agreed, Hic bubbles rn kill performance and eyes if stacked

**Comment by BlodBladelicker** [comment]
The HIC bubbles also seem to work a bit weirdly. New targets that enter the field are not warp scrambled, or unscrambled if they leave the field. 
I also saw the visual effect for the Thorax/Phobos bubble stay forever after activating the skill.

**Comment by smudge202** [comment]
Looking at the [Buff](https://github.com/kabivel/Sins-of-Empires/blob/master/GameInfo/AbilityInterdictionSphere.entity) it seems the check is ran every 60 seconds. Anything inside the sphere at the point will have the debuff for 60 seconds, though it should invalidate also on `OutOfRange` so it *should* disable when something moves out of range. However, anything moving into the bubble wouldn't have the buff applied until the 60 second tick. There doesn't seem to be a moddable trigger type that would allow you to apply the debuff when something enters range - consider this the balance for HICs not having their propulsion cut when using the bubble? 😄

**Comment by kabivel** [comment]
fixed
