### ISSUE TITLE
AI empire names

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#129]
Consider improving the AI empire names to null-sec Alliances.

**Comment by TempusLupus** [comment]
Please do

**Comment by kabivel** [comment]
Suggestions ?

**Comment by Joeyxxx** [comment]
I'll make a list

**Comment by Joeyxxx** [comment]
Shadow of xXDEATHXx
SOLAR FLEET

**Comment by TempusLupus** [comment]
Northern Wolfs
Sins of Wolfs
HAVEN
Haven's Core
Corpse Collector's Group
Psychotic Tendencies.
Fliegenbob Industries
Brothers of Tangra
Pandemic Horde
Legion of xXDEATHXx
Kids with Guns Alliance
InPanic
Blades of Grass
Prothean Alliance
Evictas.
Out of Sight.
DRONE WALKERS
Yulai Fedaration
FUBAR.
Southern Coalition

**Comment by kabivel** [comment]
implemented some names, need to reseach to see how many names we can put and how

**Comment by smudge202** [comment]
I see some names made it in for AI factions also, but that has made things a little confusing. Fighting the "Amarr Navy" who are in fact the Minmatar faction threw me a little

**Comment by kabivel** [comment]
this is random distributed. i will remove the empire names ones.
