### ISSUE TITLE
OP AMMAR DREAD RADIUS!

### ISSUE THREAD

**Issue by Malitael** [kabivel/Sins-of-Empires#132]
![image](https://user-images.githubusercontent.com/28200882/31664364-cd369626-b34d-11e7-8ea7-0c6c90f06d57.png)

**Comment by Malitael** [comment]
I burned my ass because of them

**Comment by kabivel** [comment]
dont sit on fire, for the burned ass, Fixed both amarr dreads now have same range, Minmatar dreads was with range inverted.

**Comment by Joeyxxx** [comment]
Has this been updated on the ship balancing sheet? I'm not saying the numbers are correct, but we can't just keep changing things without tracking it.

![image](https://user-images.githubusercontent.com/32372181/31761358-7b5ee958-b4af-11e7-9f48-ab8785eb398a.png)
