### ISSUE TITLE
Target Painter?

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#134]
I was playing Minmatar last night and I couldn't find a ship that actually uses the Target Painter. I assume this should be the Bellicose (or rather the Rapier as it should be)?

**Comment by kabivel** [comment]
Fixed, implented Minmatar Target Painter on lot os ships. They work, improving the aim and giving critical to hits

**Comment by Joeyxxx** [comment]
Not fixed.

**Comment by kabivel** [comment]
fixed
