### ISSUE TITLE
Player gains "Income from Abilities" at game start.

### ISSUE THREAD

**Issue by ArrowMkII** [kabivel/Sins-of-Empires#137]
At the start of the game the player gains an ISK Income from Abilities that seems to tick up from 0.3K/sec to 50K/sec and then reset back down.

See screenshots:
https://gyazo.com/572807fc5066a34cb11b320896f881eb   <--Game start
https://gyazo.com/59db76ca46d7b6174ea6d28d9792ad81  <--Ticking up
https://gyazo.com/0050b0ea3d3d37a3f7c38a5ce6850ad2 <-- Reset

Happens with all 4 races, pirates active/inactive or quickstart on/off does not change the result, nor does selecting a bigger map with more or less AI players

**Comment by kabivel** [comment]
that is the new ai in preview

**Comment by Joeyxxx** [comment]
As Kab says, this is the general approach across all SoaSE mods to help the AI.

If all players and AI gain this income, then we feel like it's fine.
