### ISSUE TITLE
Talwar it is impossible to build

### ISSUE THREAD

**Issue by Malitael** [kabivel/Sins-of-Empires#142]
![image](https://user-images.githubusercontent.com/28200882/31836612-9e64daae-b5de-11e7-9dd0-312ddb4e6276.png)

**Comment by Malitael** [comment]
Regular Сyclone is also impossible to build
![image](https://user-images.githubusercontent.com/28200882/31836765-1071df02-b5df-11e7-8347-5a772c1305f4.png)

**Comment by Malitael** [comment]
#needmorespace

**Comment by smudge202** [comment]
Tested against: 2ce4d9124a34ae40c137afaf7eef7b998aae25ba

The same is true of the Amarrian Dragoon

![dragoon-01](https://user-images.githubusercontent.com/2247869/31862908-1926927c-b73e-11e7-81c3-57ec75e834bb.png)
![dragoon-02](https://user-images.githubusercontent.com/2247869/31862910-1b3ebddc-b73e-11e7-8152-10fb532f37d4.png)

**Comment by smudge202** [comment]
Relates to #149
