### ISSUE TITLE
Factional ships give very much experience when destroyed. This makes it very fast to pump capital fleet!

### ISSUE THREAD

**Issue by Malitael** [kabivel/Sins-of-Empires#148]
![image](https://user-images.githubusercontent.com/28200882/31852565-7514adba-b682-11e7-9e94-b9974e1f49b3.png)

**Comment by smudge202** [comment]
This includes the Pirate Sansha faction. Defending against a single attack is enough to level ALL capitals to 10.

I don't think the factions give too much XP, I just think the capitals need *much* harsher XP requirements to level (about an order of magnitude). However, those levels will need to be more rewarding in some cases as highlighted in #147.

**Comment by kabivel** [comment]
New scale created for levels
