### ISSUE TITLE
T3 destroyer can't attack drones, although the description should

### ISSUE THREAD

**Issue by Malitael** [kabivel/Sins-of-Empires#151]
![image](https://user-images.githubusercontent.com/28200882/31854571-16685cfe-b6a4-11e7-9d7d-73fafe82ac35.png)

**Comment by Malitael** [comment]
While alive the carrier drones, they don't attack T3 destroyer

**Comment by kabivel** [comment]
it is set to attack but it dont, game bug 
CanFireAtFighter TRUE

**Comment by Joeyxxx** [comment]
Can we close this issue?
