### ISSUE TITLE
Amarr Covert Ops (Magnate) no Cyno

### ISSUE THREAD

**Issue by smudge202** [kabivel/Sins-of-Empires#152]
Tested against: 2ce4d9124a34ae40c137afaf7eef7b998aae25ba

Having researched everything (including Cyno's) the Magnate should have the Cynosural Field ability, but does not:

![no-cyno-01](https://user-images.githubusercontent.com/2247869/31862880-9437bffa-b73d-11e7-86f6-5e13ae1e4211.png)
![no-cyno-02](https://user-images.githubusercontent.com/2247869/31862882-95e94756-b73d-11e7-9cdf-6980fdb7a995.png)

**Comment by Joeyxxx** [comment]
The Cyno is going to be removed from frigates soon(TM).

**Comment by smudge202** [comment]
I won't re-open, but why is that @Joeyxxx ? Any ship (given fitting requirements) can fit a Cyno but cov-ops of course have access to covert cyno. Why would this be removed?

**Comment by smudge202** [comment]
I see mention of bombs in the most recent commits on the revamp branch. Contemplating switching cov-ops for stealth bomber? What would take the place of scout if that were the case?
