### ISSUE TITLE
Cloak no longer disables abilities

### ISSUE THREAD

**Issue by smudge202** [kabivel/Sins-of-Empires#153]
Tested against: 2ce4d9124a34ae40c137afaf7eef7b998aae25ba

Having tested before and after #55 was resolved I see that cloak can now be disabled again. However, it no longer disables abilities:

![cloak-abilities-01](https://user-images.githubusercontent.com/2247869/31863013-82de8610-b73f-11e7-8ce0-70bd93605e9e.png)

**Comment by kabivel** [comment]
No way arround, cloack will stay this way
