### ISSUE TITLE
DD damage too low?

### ISSUE THREAD

**Issue by smudge202** [kabivel/Sins-of-Empires#154]
Tested against: 2ce4d9124a34ae40c137afaf7eef7b998aae25ba

I don't play Eve anymore so I can't draw on recent experience, but I'd anticipate even a well fitted Dreadnought/Carrier to die at the hands of *many* DD's. I think the EHP on the caps is about right, but I'm not sure the DD's are doing enough.

Open to discussion as opposed to straight up *bug report*.

**Comment by DalaryousPT** [comment]
I personally believe the damage could indeed be higher. It takes about 8 DD's to kill a fully researched armor/shield capital, which renders titans much weaker than super-carriers. In Eve Online two DD's kill any capital.

**Comment by Joeyxxx** [comment]
Playing last night, the Avatar DD vs. Minmatar seemed to be decent. One or two hits to kill a Dread or Carrier. Unsure how far along on research they were.

**Comment by smudge202** [comment]
I need to test something, but it occurs to me it's *possible* that multiple DD's hitting a target at the same time may not effect the target as it should. Has anyone observed anything like that?

**Comment by kabivel** [comment]
fixed in other issue
