### ISSUE TITLE
Hanger Bay defaults to Squadron Management

### ISSUE THREAD

**Issue by smudge202** [kabivel/Sins-of-Empires#156]
Tested against: 2ce4d9124a34ae40c137afaf7eef7b998aae25ba

Is it possibly to have Hanger Bay's default to the home screen instead of the Squadron Management? When you're trying to build up a force of Blood Raiders, the extra click is a nuisance compared to the much lower likelihood of you needing to manage the squadrons.

For clarity, current defaults to this screen:
![hanger-default-01](https://user-images.githubusercontent.com/2247869/31863151-507e28b8-b741-11e7-85d9-7736be2b87a5.png)

Preferably, default to this screen:
![hanger-default-02](https://user-images.githubusercontent.com/2247869/31863152-5451a762-b741-11e7-9622-29a0f11a397e.png)

**Comment by smudge202** [comment]
Have confirmed that changing `entityType`in [`Bloodraisers_ModuleShipyard`](https://github.com/kabivel/Sins-of-Empires/blob/master/GameInfo/Bloodraiders_ModuleShipyard.entity#L2) from `PlanetModuleHangarDefense` to `PlanetModuleStandard` does give me the home screen, however it completely disables the *Squadron Management* aspects. I don't think this enhancement is possible, but I'll leave this open for the author in case he knows of another way?

**Comment by Joeyxxx** [comment]
@kabivel what do you think, is this possible? It would be a great quality of life improvement - since players will be spawning many ships from these hangers.

**Comment by kabivel** [comment]
Not possible.
