### ISSUE TITLE
Disable Cov-ops Auto-Explore

### ISSUE THREAD

**Issue by smudge202** [kabivel/Sins-of-Empires#160]
I wouldn't ask for this in any other mod, but with the ability to cloak a cov-ops permanently, it would make more sense to station these frigates in a system instead of leaving them on auto-explore.

In the early game (pre-cloak) auto explore makes sense, but personally I spend a lot more time de-selecting this option than would be the other way around.

Is the same true for others?

Reference: https://github.com/kabivel/Sins-of-Empires/blob/c3cfe391e1bb9f9ac91c59f9a8a517f30b64319c/GameInfo/AbilityExplore.entity#L14

**Comment by smudge202** [comment]
Per #152, @Joeyxxx implies there may be some upcoming changes to Cov-ops. Not sure how that would impact the above.

**Comment by Joeyxxx** [comment]
It has been suggested before that the autocast is removed, however early game, as you say, it's very useful. Sins has it's limitations.
