### ISSUE TITLE
HP Bars more representative of Armor/Shield HP Pool

### ISSUE THREAD

**Issue by smudge202** [kabivel/Sins-of-Empires#161]
Could ships that rely much more heavily on shield (Minmatar/Caldari) have a much larger percentage of the green/orange armour/shield bars show as shield?

![shield-bar-01](https://user-images.githubusercontent.com/2247869/31901321-0cee3b00-b819-11e7-8f12-f4e4e5b966ec.png)

For example, in the image above, 75% of the ship's health is shield. It has lost 50% of it's total health (2/3 of the shield). But looking at the small hp bars just below the ship icon and blue capacitor bar, there's no real representation of this.

**Comment by Joeyxxx** [comment]
I believe this is hard coded.

**Comment by smudge202** [comment]
I thought that might be the case, but I would have sworn that Advent in vanilla or one of the mods I've played have larger shield proportions. If I remember correctly, they still didn't represent the shield/armour split very well, but the larger shield bar was still useful. Need to load a game and check...

**Comment by Joeyxxx** [comment]
Perhaps that's worth investigating. Little things like this really make a mod shine.

**Comment by smudge202** [comment]
I've scoured both modding forums and the files themselves to no avail. I haven't given up, but it's looking like you're right - probably hardcoded. 😞

**Comment by kabivel** [comment]
hardcoded
