### ISSUE TITLE
Blackbird Description is wrong

### ISSUE THREAD

**Issue by smudge202** [kabivel/Sins-of-Empires#162]
Tested against: 2ce4d9124a34ae40c137afaf7eef7b998aae25ba

The Blackbird description fits it's Gallente ewar cruiser counter-part; it should instead indicate it's use of ECM (not sensor-dampeners). Have confirmed the cruiser itself does have the correct abilities, it's just the description.

![blackbird-desc-01](https://user-images.githubusercontent.com/2247869/31901708-2bc62a00-b81a-11e7-9c10-5a96f4975095.png)

**Comment by Joeyxxx** [comment]
Please provide the correct description.

**Comment by smudge202** [comment]
It's a good point, I can provide a [PR for the relevant lines](https://github.com/kabivel/Sins-of-Empires/blob/master/String/English.str#L24221) but I'd like to check something.... 

ECM *should* disable all weapons and abilities of enemy ships (because one cannot target anything, friendly or enemy), but it currently only disables weapons. Is ECM a guaranteed hit right now? Because I think the effect should be upgraded to include disabling abilities (break logistic chains!) but for that to be balanced it must be 20-40% chance only and must not effect triaged capitals at all?

**Comment by Joeyxxx** [comment]
As far as I know ECM does not affect Capital ships. It disables weapons but not skills. I suspect this is an engine limitation.

I suppose descriptions are minor bugs, you're right.

**Comment by smudge202** [comment]
Do you think it *should* disable skills? I believe I can make the ECM ability do this, but I was wondering if there was a reason for not doing it? I need to look into making the effect chance based if it isn't already.

**Comment by Joeyxxx** [comment]
Personally, I feel like disabling the weapons is enough.

**Comment by smudge202** [comment]
Fair enough, I'll put together a PR with an updated description and leave the abilities as-is

**Comment by kabivel** [comment]
fixed
