### ISSUE TITLE
Repair Platform/Hanger Bay incorrect name

### ISSUE THREAD

**Issue by smudge202** [kabivel/Sins-of-Empires#163]
Tested against: 2ce4d9124a34ae40c137afaf7eef7b998aae25ba

I believe the description of the *Hanger Bay* has been swapped with the name *somewhere*:

![repair-platform-01](https://user-images.githubusercontent.com/2247869/31901802-787324c0-b81a-11e7-905e-aaad5917b7f8.png)

**Comment by smudge202** [comment]
Similar to #162, I'm pretty sure this is a bug (albeit a minor one), not enhancement, @Joeyxxx ?

**Comment by kabivel** [comment]
fixed

**Comment by kabivel** [comment]
FIXED
