### ISSUE TITLE
Triage Module upgrade for no benefit

### ISSUE THREAD

**Issue by smudge202** [kabivel/Sins-of-Empires#164]
At level 10, Triage Carriers have the option to upgrade their *Triage Module*. However, there does not appear to be any benefit in doing so?

![triage-upgrade-01](https://user-images.githubusercontent.com/2247869/31901924-fbe9086a-b81a-11e7-8e37-e530145aafc7.png)

**Comment by Joeyxxx** [comment]
From what I have noticed - the FAX nor the Carrier automatically uses Triage in any situation.

**Comment by smudge202** [comment]
Agreed, and the ability itself isn't particularly clear. Cloak for example is toggle on/off, whilst for example, Afterburner is a timed benefit. Triage seems to be a timed benefit, but longer than the ability cooldown timer and no indication of when the triage ends (except that the cooldown timers of other abilities goes back up)?

**Comment by Joeyxxx** [comment]
Ship's don't handle the Triage ability very well to be honest. Probably worth removing it and replacing with something more interesting.

**Comment by smudge202** [comment]
I'm going to play with this ability a little to see if I can get better behaviour from it. Personally, I love the logistics side of Eve and therefore this mod, though the latter may need more balancing. I think simply setting the cooldown to the buff duration will clear up the confusion about it's usage. I'll also play with the AI/auto usage settings to see if it can be made more viable in that regard.

For the OP, I think the best thing to do is either increase the amount repaired / cap transferred, or lower the cooldown further. Triage modules in eve are responsible for both; increasing the amount transferred I think would be very viable in this mod.

**Comment by kabivel** [comment]
made some changes to triage and siege, they should be oposed but with same stats
