### ISSUE TITLE
Logistics Cruisers only use 1 Repair?

### ISSUE THREAD

**Issue by smudge202** [kabivel/Sins-of-Empires#165]
I'd like to check with others, but it's been my observation that logistic cruisers of any race only seem to use one of their repair abilities, and that one they use very slowly compared to the cooldowns.

I'm wondering if it might be worth doubling the HP amount of one of those repairs and getting rid of the second repair ability to try and free up same CPU cycles, especially if the ability is only ever triggered manually.

**Comment by Joeyxxx** [comment]
They seem to work better when having two of the remote repair skills.

**Comment by smudge202** [comment]
Have you seen the second repair ability being used? I've only witnessed the first skill. It *seems* like the game engine is running a pass to determine whether to use the skill on a slower timer than the cooldown, so it only ever uses one. I don't know if that's the case, but what I have observed is that only one of the two repairs are used, and they used much slower than *on-cooldown*.

**Comment by Joeyxxx** [comment]
I have noticed the Basilisks using skill1 and waiting until that's cooled down and then using skill2. When there is only skill1 it takes longer for the game to realise and re-use it.

**Comment by smudge202** [comment]
Ok, fair enough. I'll leave it alone then. Happy to close this as a "Best we can get given engine limitations"
