### ISSUE TITLE
Loki using Tengu icon

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#169]
^^

**Comment by kabivel** [comment]
Need print

**Comment by Joeyxxx** [comment]
![image](https://user-images.githubusercontent.com/32372181/31962658-115ebbb4-b8f6-11e7-802d-e7ed5b821b76.png)

**Comment by kabivel** [comment]
it is fixed for me, what branch you are ?

**Comment by Joeyxxx** [comment]
Master, of course. Downloaded it earlier today.

**Comment by kabivel** [comment]
fixed on ai
