### ISSUE TITLE
Cyclone Envoy in Cruisers

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#170]
![image](https://user-images.githubusercontent.com/32372181/31962856-aa77fcca-b8f6-11e7-9ea7-4eacbaff6016.png)

**Comment by kabivel** [comment]
all envoy ships are in this position, what is the bug ?

**Comment by Joeyxxx** [comment]
Ah, perhaps there is no bug then. Do you build the Cyclone from the Frigates list? Seems odd.
