### ISSUE TITLE
Minmatar diplomacy research

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#173]
Requires Prophecy BPO not Cyclone.

Research names: Arbitrate Tariff / Settlers / Worthy cause

![image](https://user-images.githubusercontent.com/32372181/31963396-660c3acc-b8f8-11e7-9b88-3d2065a39aec.png)

**Comment by kabivel** [comment]
need the name of the 3 researchs to fix

**Comment by Joeyxxx** [comment]
Yes, they are in the description...

"Research names: Arbitrate Tariff / Settlers / Worthy cause"

**Comment by kabivel** [comment]
fixed
