### ISSUE TITLE
Triage affected by its ability cooldown modifier

### ISSUE THREAD

**Issue by HexenDot** [kabivel/Sins-of-Empires#175]
if it autocast when the reps were activated it wouldn't be that big of a deal though

**Comment by smudge202** [comment]
More as a reminder to myself as I planned to look at this anyway, ref discussion in #164 (OP seems to have been resolved - not tested - but discussion warrants a further look I think)

**Comment by kabivel** [comment]
it affect all abilities, even it self nothing to do here.

**Comment by smudge202** [comment]
I'm not sure that's true, @kabivel. Looking at [`AbilityTriageMode.entity`](https://github.com/kabivel/Sins-of-Empires/blob/Ai_Revamp/GameInfo/AbilityTriageMode.entity) and [`AbilityTriageModeShield.entity`](https://github.com/kabivel/Sins-of-Empires/blob/Ai_Revamp/GameInfo/AbilityTriageModeShield.entity) clearly the intended cooldown times is 120 seconds at all levels.

Per your [commit yesterday](https://github.com/kabivel/Sins-of-Empires/commit/98090e1d1a563435a51d6570535aedb206ea4e25) changing [`BuffTriageMode.entity`](https://github.com/kabivel/Sins-of-Empires/blob/Ai_Revamp/GameInfo/BuffTriageMode.entity) and [`BuffTriageModeShield.entity`](https://github.com/kabivel/Sins-of-Empires/blob/Ai_Revamp/GameInfo/BuffTriageModeShield.entity) from a 4.4 ability cooldown improvement across the board to 3.5/3.9/4.0/4.2 simply multiplying the cooldown in `AbilityTriageMode[Shield]` to 120 * 3.5/3.9/4.0/4.2 respectively should work to synchronise the cooldowns with the ability `finishCondition`?

i.e.

```
cooldownTime
	Level:0 420.000000
	Level:1 468.000000
	Level:2 480.000000
	Level:3 504.000000
```

This should equate to all of these abilities actually cooling down after 120 secs?

*Sidenote:*

Level | Rate | Difference
--- | --- | ---
1 | 3.5 | +3.5
2 | 3.9 | +0.4
3 | 4.0 | +0.1
4 | 4.2 | +0.2

^ There doesn't seem to be any discernible pattern to these buffs? Level 3 is almost pointless. Buffs should either incline or decline in the difference they make depending on how you want to balance things.

Given Levels 2, 3 & 4 unlock at ship levels 4, 5 & 6 respectively, I'm not sure this makes much sense?

**Comment by smudge202** [comment]
Another side note, the change was only made to Armour tanking force auxillaries. [`AbilityTriageModeShield.entity`](https://github.com/kabivel/Sins-of-Empires/blob/Ai_Revamp/GameInfo/AbilityTriageModeShield.entity) did not receive the same update, so [`Caldari_Shi-Carrier_Triage_Chimera.entity`](https://github.com/kabivel/Sins-of-Empires/blob/826605fc316f6ae7b493553cf3f8ae98197b265a/GameInfo/Caldari_Ship_Carrier_Triage_Chimera.entity) and [`Minmatar_Ship_Carrier_Triage_Lif.entity`](https://github.com/kabivel/Sins-of-Empires/blob/826605fc316f6ae7b493553cf3f8ae98197b265a/GameInfo/Minmatar_Ship_Carrier_Triage_Lif.entity) haven't received this change yet - though I appreciate this in on the `Ai_Revamp` branch so isn't official yet.
