### ISSUE TITLE
Need Print of ingame DD damage of all titans.

### ISSUE THREAD

**Issue by kabivel** [kabivel/Sins-of-Empires#176]
Need Print of ingame DD damage of all titans.

I think Doonsdays damages are wrong, need print of all titans doonsday ability.

**Comment by smudge202** [comment]
I ran up a fitting tool quickly, the Judgement does 1.5mill damage with a level 5 char. Do you just want numbers from a fitting tool or do you need people playing Eve, in a Titan, to check the output?

**Comment by Joeyxxx** [comment]
I think Kab means within the mods - because he cannot play the game atm.

**Comment by BlodBladelicker** [comment]
Amarr:
Titan - Avatar
![titan avatar doomsday](https://user-images.githubusercontent.com/32543932/32049578-d7d643d6-ba4d-11e7-8d48-39ce108c4d34.png)

Titan - Molok
![titan molok doomsday](https://user-images.githubusercontent.com/32543932/32049590-dfce6ad2-ba4d-11e7-970a-945cab6a26e6.png)

Capital - Avatar
![capital avatar doomsdayy](https://user-images.githubusercontent.com/32543932/32049597-e5694610-ba4d-11e7-9b71-12d4e0a12e91.png)

**Comment by BlodBladelicker** [comment]
Gallente
Titan - Erebus
![titan erebus doomsday](https://user-images.githubusercontent.com/32543932/32049620-f50a6810-ba4d-11e7-8dd5-89f28eb95366.png)

Titan - Vanquisher
![titan vanquisher doomsday](https://user-images.githubusercontent.com/32543932/32049626-f9a96998-ba4d-11e7-8cd9-57429572f8b9.png)

Capital - Erebus
![capital erebus doomsday](https://user-images.githubusercontent.com/32543932/32049629-fe91da3a-ba4d-11e7-9ad9-3d0f471697c4.png)

**Comment by BlodBladelicker** [comment]
Minmatar
Titan - Ragnarok
![titan ragnarok doomsday](https://user-images.githubusercontent.com/32543932/32049643-07d62592-ba4e-11e7-931f-f257d0fe3186.png)

Capital - Ragnarok
![capital ragnarok doomsday](https://user-images.githubusercontent.com/32543932/32049645-0c161e14-ba4e-11e7-9850-f82960748a79.png)

**Comment by BlodBladelicker** [comment]
Caldari
Titan - Leviathan
![titan leviathan doomsday](https://user-images.githubusercontent.com/32543932/32049655-16b36228-ba4e-11e7-90b7-4a0c5379bc00.png)

Capital - Leviathan
![capital leviathan doomsday](https://user-images.githubusercontent.com/32543932/32049659-1cc03a06-ba4e-11e7-8a31-734ba18946c4.png)

**Comment by kabivel** [comment]
as i feared was wrong. fixed
