### ISSUE TITLE
Capital armor self-repair typo

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#179]
In the description of AbilityArmorRepairerCapital it states 'Restore a great amount of own Shield HP' which should be Armor HP.

**Comment by Joeyxxx** [comment]
Please provide a screenshot from within the game.

**Comment by BlodBladelicker** [comment]
![archon self-rep typo](https://user-images.githubusercontent.com/32543932/32049555-c100f23c-ba4d-11e7-9211-67ec694a3bca.png)

**Comment by kabivel** [comment]
fixed
