### ISSUE TITLE
Gallente wrong last mining research icons

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#181]
Bistot mining is using the icon for Mercoxit
Megacyte refining is using the icon for Zydrine

**Comment by Joeyxxx** [comment]
Please provide a screen shot from within the game.

**Comment by BlodBladelicker** [comment]
![20171024173129_1](https://user-images.githubusercontent.com/32543932/32043581-6ffa7744-ba3b-11e7-893b-759c19b83b32.jpg)
![20171024173130_1](https://user-images.githubusercontent.com/32543932/32043585-71abac16-ba3b-11e7-97e9-5ec3ac77b612.jpg)

**Comment by kabivel** [comment]
on our universe is right, CCP is using it wrong on EVE online. Fixed
