### ISSUE TITLE
Oneiros buff icon wrongly displayed

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#182]
As per the screenshot, it's not displaying properly. 
![20171024173443_1](https://user-images.githubusercontent.com/32543932/32004850-0dc7751a-b9a3-11e7-9bc8-a66e39e60235.jpg)

**Comment by Joeyxxx** [comment]
![image](https://user-images.githubusercontent.com/32372181/32041897-be9d763e-ba2d-11e7-9b1c-67345a831bb3.png)

**Comment by kabivel** [comment]
fixed
