### ISSUE TITLE
(gallente) Revenant build time and self-buff

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#183]
The build time for the revenant is currently rather long at 643 seconds build time vs 107 seconds for the Vendetta. 
The self buff currently makes the ability cooldowns longer instead of shorter(like other supercarriers) and also has a few mistakes:

Called Drone Miss(i)le Launcher when it only buffs the Revenant  (lacking the i in Missile elsewise)

The description also states: Order the fighter Strike Craft to Shoot a Voll(-y)ey Of Missiles on ta(r)get
Which doesn't equal what the ability actually does, aside from creative use of capital letters and volley and target having typos.

![20171024175432_1](https://user-images.githubusercontent.com/32543932/32005068-a22a38be-b9a3-11e7-96f6-3a122b65238a.jpg)

**Comment by Joeyxxx** [comment]
I would suggest creating two separate issues here; one for the build time (which may indeed require balancing) and one for the ability description.
