### ISSUE TITLE
Race selection images

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#185]
Gallente and Caldari use very similar images, I would suggest that's not correct.

Also, the smaller image is Amarr for both.

![image](https://user-images.githubusercontent.com/32372181/32014056-e91a1e40-b9b4-11e7-909a-9825561cebd4.png)

And the Amarr and Minmatar smaller images are Caldari / Gallente

![image](https://user-images.githubusercontent.com/32372181/32014091-062f0b8a-b9b5-11e7-850c-f0acff3d2186.png)

**Comment by kabivel** [comment]
Gallente and Caldari images are Vader and Goliath, wont be changed. Minmatar i will put one of my own.

**Comment by Joeyxxx** [comment]
They are images of their Eve characters?

It's rather confusing when selecting races - Amarr and Minmatar are obvious but Caldari and Gallente look identical.

**Comment by kabivel** [comment]
They are both caldari, suckkers,
