### ISSUE TITLE
Aeon Super Carrier Refit typo

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#188]
'survavility' should be 'survivability'

![aeon refit typo](https://user-images.githubusercontent.com/32543932/32049905-31a6991e-ba4f-11e7-984c-9461a823bc1c.png)

**Comment by smudge202** [comment]
Here: https://github.com/kabivel/Sins-of-Empires/blob/master/String/English.str#L25649

**Comment by smudge202** [comment]
Similar typos existed for some of the cruisers resist upgrades so I'll grab those too:

https://github.com/kabivel/Sins-of-Empires/blob/master/String/English.str#L25775
https://github.com/kabivel/Sins-of-Empires/blob/master/String/English.str#L25781

**Comment by Joeyxxx** [comment]
#199 

The descriptions for all Super carriers should be similar

**Comment by kabivel** [comment]
why learn english ??? fixed
