### ISSUE TITLE
Revenant build time

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#189]
Currently the Revenant build time is rather long. In the dev session I just did, it was 818 seconds vs 136 seconds for the Revenant and Aeon(also Capital Avatar) respectively.
![rev-aeon build time comparison](https://user-images.githubusercontent.com/32543932/32050147-197133bc-ba50-11e7-8bae-e092bc0262d8.png)
![rev-aeon build time comparison2](https://user-images.githubusercontent.com/32543932/32050150-1a6003ca-ba50-11e7-812f-b2b14614170f.png)

**Comment by Joeyxxx** [comment]
A longer build time is warranted for such an expensive and powerful ship. What build time would you suggest?

**Comment by BlodBladelicker** [comment]
Comparing it to the Wyvern with max research on Caldari faction:
Lvl 1 Wyvern: No abilities
Hull: 149.500
Armor: 20
Shield: 350.000
Base resist: 15%
Capacitor: 144.000
Fighters: 15
Single bomber(mantis) stats:
Hull: 5750
Armor: 10
Autocannon DPS: 44
Missile DPS: 319
Total DPS: 660 + 4785 = 5445

Lvl 1 Revenant: No abilities
Hull: 79.062
Armor: 0
Shield: 192.500
Base resist: 15%
Capacitor: 18.720
Fighters: 10
Single bomber(mantis) stats:
Hull: 4600
Armor: 13
Autocannon DPS: 44
Missile DPS: 638
Total DPS: 440 + 6380 = 6820



Lvl 10 Wyvern: Max Tank/Damage
Hull: 284.050
Armor: 20
Shield: 722.600
Base resist: 25%
Capacitor: 273.600
Fighters: 15
Single bomber(mantis) stats:
Hull: 5750
Armor: 10
Autocannon DPS: 52
Missile DPS: 383
Total DPS: 780 +5745 = 6525

Total DPS:
Lvl 10 Revenant: Max Tank/Damage
Hull: 86.178
Armor: 0
Shield: 267.425
Base resist: 25%
Capacitor: 35.568
Fighters: 10
Single bomber(shadow) stats:
Hull: 4600
Armor: 13
Autocannon DPS: 52
Missile DPS: 766
Total DPS: 520 + 7660 = 8180

With the current revenant/shadow stats. It is far from substantially more powerful than the Wyvern, therefor I don't think it warrants such a long build time. This issue is even more the case for Armor races(amarr/gallente) as the Revenant in such cases lacks armor tank to really be worth considering.

Given the current stats. I'd bring the build time to 150 seconds at most. Preferably bringing it in line with other supercarriers at 136 seconds base build time.

**Comment by smudge202** [comment]
> Disclaimer: I've been out of eve for several years so don't know current meta at all

When I was playing though, ships like Revenant wouldn't have taken much longer to build than non-faction counterparts. They would have been considered a lot more expensive though (so price is probably accurate). I think they should have a slight advantage over non-faction ships, but build time can probably be reduced without hurting balance too badly.

I agree, for armour races ships like the Revenant are at a disadvantage (as-is your starter Rorqual and Orcas...)

**Comment by Joeyxxx** [comment]
Hmm interesting stats on the Revenant, I suspect it could do with a considerable buff. Personally, I would like to see pirate and faction ships much strong that the vanilla counterparts.

**Comment by smudge202** [comment]
Bear in mind that in Eve, pirate and Faction only have one or two extra bonuses of about 15% for a given stat. They're certainly not super-powered by comparison. Though, they're often also fitted more expensively so maybe the bonus overall adds up to something closer to 40%?

**Comment by Joeyxxx** [comment]
Indeed, I was assuming they were fit with superior fittings. Possibly something like 40% but the cost and build time will of course need to be updated to reflect.

**Comment by kabivel** [comment]
Fixed XD
