### ISSUE TITLE
Projected ECM Burst description

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#190]
The description states there is a 'chance' but as far as I know, it is certain that the enemy will 'lose locks'.

![revenant ecm burst descriptino change plss](https://user-images.githubusercontent.com/32543932/32050172-2dbdbeda-ba50-11e7-8de0-4f6b941279aa.png)

**Comment by smudge202** [comment]
Agreed, just checked the files. Seems to effect all targets for 40 seconds, not chance based.

**Comment by smudge202** [comment]
Contemplated updating the description as part of my #206 PR but better that @kabivel confirms it's the description that's wrong, not the ability (should it be chance based?).

**Comment by kabivel** [comment]
fixed descrpition
