### ISSUE TITLE
Fighter Support Unit typo

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#191]
States it increases number of fighters per squad, when it increases fighter stats.

![revenant fighter support unit typo](https://user-images.githubusercontent.com/32543932/32050247-65577d90-ba50-11e7-87fe-c46e8e45e275.png)

**Comment by Joeyxxx** [comment]
Please provide the proposed description so that it can be copy and pasted.

**Comment by smudge202** [comment]
How about:

> Improves the characteristics of your drones to both improve their survivability and increase their damage output

**Comment by kabivel** [comment]
fixed
