### ISSUE TITLE
Rorqual Panic Description Typo

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#192]
States it is 2 minutes, when it is 1 minute. 

![rorqual panic typo](https://user-images.githubusercontent.com/32543932/32050279-7ce6fbde-ba50-11e7-8035-b8d14b850bb2.png)

**Comment by Joeyxxx** [comment]
Please provide the proposed description so that it can be copy and pasted.

**Comment by smudge202** [comment]
"The Pulse Activated Nexus Invulnerability Core makes the Rorqual invulnerable for 60 seconds"

**Comment by kabivel** [comment]
fixed
