### ISSUE TITLE
Titan Leviathan Phenomena not working

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#193]
[I didn't test it in a proper round, only as spawned ship in dev.exe]

Despite having upped the ability for the Caldari Phenomena it didn't appear in the ability slots.

![titan leviathan no phenomena](https://user-images.githubusercontent.com/32543932/32050316-a00d806a-ba50-11e7-87a5-1fec1fd0a035.png)
![titan leviathan no phenomena2](https://user-images.githubusercontent.com/32543932/32050318-a0fb4ef8-ba50-11e7-8a62-cdbb2f5d396f.png)

**Comment by smudge202** [comment]
Is that the Titan Titan or Capital Titan (looks like the Titan Titan but better to check)?

**Comment by BlodBladelicker** [comment]
That is indeed the Titan Titan. The capital Titan doesn't have the phenomena ability as far as I am aware.

**Comment by Joeyxxx** [comment]
We were to them as Command Titans, if that helps with the terminology.

**Comment by smudge202** [comment]
Ah, files distinguish them as Titan and Capital Titan respectively. Good to know, thanks.

**Comment by kabivel** [comment]
Can someone teste this with others titans ?

**Comment by kabivel** [comment]
tested working
