### ISSUE TITLE
Dragonfly typo

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#194]
"These small craft are formidably powerful Gallente fighters" 
Suggested: "These small craft are formidable Caldari fighters"  
(English isn't my first language so I might very well be wrong, but isn't formidably powerful redundant?)

![wyvern dragonfly typo](https://user-images.githubusercontent.com/32543932/32050364-d428dd0e-ba50-11e7-9e16-c6bbc12dfd3f.png)

**Comment by smudge202** [comment]
Both this and the other suggestion for drone descriptions are good (English Speaker).
