### ISSUE TITLE
Gallente Vendetta has no Satyrs

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#195]
As per the title, the Vendetta only has the Firbolg and Cyclops, and no Satyrs.
![vendetta lacking satyrs](https://user-images.githubusercontent.com/32543932/32050721-25716b8a-ba52-11e7-98e9-33f2a3046c5c.png)

**Comment by Joeyxxx** [comment]
I believe it's a direct copy of the Nyx. What should they both have?

**Comment by BlodBladelicker** [comment]
Aeon, Nyx, Hel and Wyvern has all 3 types of fighters. 
Checking all of the faction supers:
SerpentisVendetta has fighter+bomber
GuristasWyvern has fighter+bomber
BloodRaider1Aeon has fighter+bomber
BloodRaider2Aeon has all 3(bloodraider is twice in spawn menu)
AngelHel has all 3

So it's a bit inconsistent in any case, it's weird not to have the anti-fighter options on faction supers though I'd argue.

**Comment by Joeyxxx** [comment]
I'd say keep it simple. I doubt anybody would build a Super and use Fighters. It's all about the Fighter Bombers.

Remove all and replace with appropriate faction bombers?

**Comment by BlodBladelicker** [comment]
That is a fair point. I have never build superiority fighters, smartbombs are simply more useful for that. 
Faction bombers or an ability change so they have more DPS in comparison to their non-faction counterpart I would agree with.

**Comment by kabivel** [comment]
fixed
