### ISSUE TITLE
Titan Ragnarok weapon upgrade typo

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#198]
"modueles" should be 'modules'

![titan ragnarok damage upgrade typo](https://user-images.githubusercontent.com/32543932/32050953-17e2dc5a-ba53-11e7-9222-e1ae54235093.png)

**Comment by Joeyxxx** [comment]
I think we can improve this description with:

"Refit the Titan's weapons with T2, Faction and Officer variants."
