### ISSUE TITLE
Shield supercarrier refit ability name/description/effect

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#199]
The self buff currently makes the ability cooldowns longer instead of shorter(like other supercarriers) and also has a few mistakes:

Called Drone Miss(i)le Launcher when it only buffs the ship itself (lacking the i in Missile elsewise)

The description also states: Order the fighter Strike Craft to Shoot a Voll(-y)ey Of Missiles on ta(r)get
Which doesn't equal what the ability actually does, aside from creative use of capital letters and volley and target having typos.

![20171024175432_1](https://user-images.githubusercontent.com/32543932/32050989-410e5938-ba53-11e7-88f9-3e798323603d.jpg)

**Comment by Joeyxxx** [comment]
I thought this was a passive skill to increase the 'tank' of a Supercarrier, why is there a skill cool down?

**Comment by smudge202** [comment]
I suspect the cooldown is a mistake, but it's unclear given the recent changes to Dreads.

**Comment by BlodBladelicker** [comment]
Both Armor refit and Shield refit has the ability cooldown (de)buff.
Basically, this makes it so they can use their bursts and smartbombs more or less often, aside from increasing tank for the super. 
Armor supers can use their abilities more often due to the buff
Shield supers can use their abilities less often due to the debuff
one of them has a wrong attribute(lacking or having a "-" when it shouldn't)

**Comment by Joeyxxx** [comment]
These skills should be constant across all super carriers and perhaps be named "Super carrier refit" and scale when ability level is increased.

Increase maximum shield / hull
Increase damage resistance / armor
Decrease ability cool down

Description "Refit the Super carrier with T2, faction and officer fittings."

*It's nice to mention Eve terminology such as "T2" etc.*

No need to mention fighters or fighter bombers.

**Comment by kabivel** [comment]
Q: Is it possible to have different descriptions on ability levels? i.e. Level 1 says XXX, level 2 says YYY?
Nops
fixed
