### ISSUE TITLE
Specular Maps

### ISSUE THREAD

**Issue by Mavrik347** [kabivel/Sins-of-Empires#2]
Your specular maps are broken, they will look very shiny in-game and shadows will not be depicted properly. Contact me for fix.

**Comment by kabivel** [comment]
Hi, can you join discord and contact me there ?

**Comment by vader111** [comment]
i'm in the process of completely revamping the textures, so no more metallic shiny ships

**Comment by vader111** [comment]
by full release this issue will be fixed
