### ISSUE TITLE
Suggestion: Revenant Shadow Squads

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#201]
Currently the Revenant only has 1 squad of 10 shadows. This causes the build time for the revenant's DPS source to be incredibly long. 
The shadow squad has a build time of 85 seconds per fighter(10 per squad, 1 squad)
The cyclops squad has a build time of 33 seconds per fighter(3 per squad, 5 squads)
This causes the total build time for all fighters to be:
Shadows: 850 seconds
Cyclops: 99 seconds

Suggestion:
Give the Revenant 5 squads of 2 fighters per squad. With a build time of 49.5 seconds per fighter.

**Comment by Joeyxxx** [comment]
Sounds like a sensible suggestion.

**Comment by smudge202** [comment]
The only downside I can think of to this suggestion would be performance (rendering and computing more fighter squadrons). Worth mentioning, that's all.

**Comment by Joeyxxx** [comment]
Bingo, the squads were reduced to improve performance. However, if you have more than one Revenant you're probably ready to steam-roll other players(?).

**Comment by smudge202** [comment]
To be fair, by the time you get to building Revenants, there's probably only 2 players left, posturing for the largest fleet battles you're likely to see during the match. Maybe hitting performance at that level isn't such a good idea?

**Comment by BlodBladelicker** [comment]
Given that other supercarriers have 5 squads, what would it matter if revenants did as well?  You could bring it back to 3 squads of 5 for supercarriers and 2 squads of 5 for revenants if that is the case. But given the hundreds of battleships and others with their own drones, what is another 200 with 50 revenants.

**Comment by smudge202** [comment]
Fair point. I don't see the harm personally.

**Comment by kabivel** [comment]
fixed
