### ISSUE TITLE
Nestor has cloak. Invulnerable (temporary) logi

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#202]
The nestor has a cloak, due to cloaks still allowing ability use this causes the nestor to be an invulnerable logi ship. Passive regen is disabled so eventually they'd run out of cap, but it would take a while.

![20171024182104_1](https://user-images.githubusercontent.com/32543932/32059583-dae3c5c0-ba6c-11e7-9399-7077f4677d9d.jpg)

**Comment by smudge202** [comment]
Per discussion in #186, what should the cloak be replaced by? (Ref: https://github.com/kabivel/Sins-of-Empires/issues/186#issuecomment-339632680)

**Comment by Joeyxxx** [comment]
Perhaps the generic afterburner / MWD. These ships don't really warrant the time and cost investment.

**Comment by smudge202** [comment]
I'll throw in a MWD to replace the cloak in a PR later on/tomorrow

**Comment by kabivel** [comment]
replaced with afterburner
