### ISSUE TITLE
All upgrades reset on  home planet

### ISSUE THREAD

**Issue by sseebbee** [kabivel/Sins-of-Empires#203]
Just started game as Caldari, placed two civilian res stations and two military, started to upgrade logistics upgrade on my home planet. I close it and my first colony got got made. I look at research tab and I dont have any avaible research due to lack of stations. I look back at my main planet and all upgrades are gone. https://i.imgur.com/lBJa8f2.jpg

**Comment by Joeyxxx** [comment]
Well this is very strange...

**Comment by sseebbee** [comment]
have tried a few times but can't managed to do it. Have no clue what action actually caused it to do so. 
Will re-write it if it happen again

**Comment by Joeyxxx** [comment]
OK I'll close this issue for now. Thanks.
