### ISSUE TITLE
Cromont not attacking drones

### ISSUE THREAD

**Issue by sseebbee** [kabivel/Sins-of-Empires#205]
The cormont won't attack drones. Only way to do it, is by manually scrolling in and right-clicking the model. if I do it zoomed out, the attack order goes on the ship owner of the drones.

**Comment by smudge202** [comment]
Ref #151

**Comment by BlodBladelicker** [comment]
This is caused by the weapon type being wrong for the ship. It is currently "ANTILIGHT" and it needs to be "ANTIVERYLIGHT" in order to directly attack and chase drones.

**Comment by Joeyxxx** [comment]
Very good spot!

**Comment by kabivel** [comment]
lets try

**Comment by Joeyxxx** [comment]
I'm going to reopen this so it's easier to track - we need to test this out and then apply to the other race's destroyers.

**Comment by Joeyxxx** [comment]
This worked, please apply to other races - not just Caldari. @kabivel

**Comment by kabivel** [comment]
fixed, now all destroyers shoot drones
