### ISSUE TITLE
Leviathan Doomsday ability upgrade does not increase stats

### ISSUE THREAD

**Issue by sseebbee** [kabivel/Sins-of-Empires#207]
The other DD gives lower cool-down but the Levi DD doesn't change anything, making it a useless upgrade.

**Comment by Joeyxxx** [comment]
Please can you confirm if this is the Titan or Command Titan (which is built in the Titan factory)

**Comment by smudge202** [comment]
Looks like it's the Command Titan that doesn't have any benefit from leveling:

Command Titan
https://github.com/kabivel/Sins-of-Empires/blob/6714c25facf17c8c07aa9d85fb50d8843a4042a9/GameInfo/AbilityOblivion.entity#L49-L53

Titan:
https://github.com/kabivel/Sins-of-Empires/blob/6714c25facf17c8c07aa9d85fb50d8843a4042a9/GameInfo/AbilityOblivionCapital.entity#L53-L57

**Comment by kabivel** [comment]
fixed
