### ISSUE TITLE
Remove Refinery Moon Mining

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#213]
Allows for infinite resources.

We need to remove this until the concept development has been completed.

**Comment by TempusLupus** [comment]
It dosn't need to be removed, jus reduce the resources income from it lol

**Comment by Joeyxxx** [comment]
The whole concept requires more thought. For now it should be removed as it's game breaking.

**Comment by kabivel** [comment]
I will remove temporary, vader have foughts on this ?
