### ISSUE TITLE
Locust Squads Description

### ISSUE THREAD

**Issue by robohunterx** [kabivel/Sins-of-Empires#215]
The Locust fighters description lists them as being "Strong vs Cruisers then Frigates" (The rest of the description is right though) in the green text.

**Comment by Joeyxxx** [comment]
Please provide a screenshot.

**Comment by robohunterx** [comment]
https://cdn.discordapp.com/attachments/294013487234154497/374539893445230593/unknown.png

It's the same for the Caldari Carrier as well.

**Comment by kabivel** [comment]
And the problem is ?

**Comment by robohunterx** [comment]
The green text should read like "Strong versus other fighters and Drones" or etc, not frigates and cruisers etc.

**Comment by kabivel** [comment]
fixed
