### ISSUE TITLE
Caldari Dreadnought Siege Cooldown

### ISSUE THREAD

**Issue by robohunterx** [kabivel/Sins-of-Empires#216]
Not really sure if an issue or bug, but currently the cooldown is set to 150, while the siege time is a standard 300 seconds. This sorta makes for a weird moment where I'm not sure how much longer the dread will be in siege, and I can't tell if hitting the siege multiple times would actually keep adding 300+ seconds onto the already running timer.

**Comment by Joeyxxx** [comment]
Yeah, this is annoying. The cool down should be the length of the ability use.

**Comment by robohunterx** [comment]
https://cdn.discordapp.com/attachments/294013487234154497/374540679730167819/unknown.png

**Comment by kabivel** [comment]
both 300 now
