### ISSUE TITLE
Caldari Phoenix

### ISSUE THREAD

**Issue by robohunterx** [kabivel/Sins-of-Empires#217]
Hey dudes, I'm only seeing a single caldari dread, the anti-capital one. Not sure if what happened was you merged the two anti-cap and HAW dreads into one, and just gave the Phoenix an ability for "Anti-capital" guns or etc (Btw, I think that's a pretty awesome idea from a gameplay standpoint, sorta :D )...if that's the case I guess the only issue is it's still named "Anti Capital Phoenix" etc etc.

**Comment by BlodBladelicker** [comment]
They are indeed currently merged into 1 ship. Though I don't think the 'anti-capital' thing works as the title would imply, since it makes the dread stronger against everything rather than just capitals.

**Comment by robohunterx** [comment]
Could perhaps have a reduction to the DPS against subcaps when activated, however I'm not sure if the ai would use this properly.

**Comment by Joeyxxx** [comment]
They have had a large reduction in damage vs. non-capitals already. If you are proposing further reductions please provide us with some numbers.

**Comment by robohunterx** [comment]
Ah Kk, nope that's fine, the balance right now definitely has you required to field a subcap fleet for taking down another subcap fleet, so that's good.
