### ISSUE TITLE
Cormorant's "Warp Disruption Bubbles"

### ISSUE THREAD

**Issue by robohunterx** [kabivel/Sins-of-Empires#218]
They're still named Missile Battery's or whatnot, just small thing I've noted.

**Comment by Joeyxxx** [comment]
Please provide a screen shot.

**Comment by robohunterx** [comment]
https://cdn.discordapp.com/attachments/294013487234154497/374540202179297290/unknown.png

Only seen on the caldari so far, I have not checked the other 3 races

**Comment by kabivel** [comment]
fixed
