### ISSUE TITLE
Hel Shield is quite high

### ISSUE THREAD

**Issue by Killervin** [kabivel/Sins-of-Empires#228]
In the BETA Version 1.0 the Hel Minmatar super-carrier has about 1 million shield points

**Comment by kabivel** [comment]
the values are thoses

MaxHullPoints
	StartValue 375000.000000
	ValueIncreasePerLevel 37500.000000
MaxShieldPoints
	StartValue 613000.000000
	ValueIncreasePerLevel 61300.000000
it is not 1 milion
