### ISSUE TITLE
Incorrect model for Wyvern

### ISSUE THREAD

**Issue by Tangopapa7** [kabivel/Sins-of-Empires#231]
Wyvern model currently shows the same model as the Hel and not the unique one it should.

**Comment by smudge202** [comment]
This will need a screenshot? Do you mean the Icon, the Ship model in the *overview*, the 3D model?

**Comment by Tangopapa7** [comment]
Sorry I wasn’t clear it’s the 3D model that shows as a Hel

**Comment by vader111** [comment]
fixed for next version
