### ISSUE TITLE
Leviathan Game Crash

### ISSUE THREAD

**Issue by Tangopapa7** [kabivel/Sins-of-Empires#232]
Any time you either build or try to spawn a leviathan using dev commands, the game crashes out.

**Comment by Joeyxxx** [comment]
Have you tested this outside of Dev mode?

**Comment by Tangopapa7** [comment]
I'll give it a go outside Dev mode and get back to you

**Comment by Tangopapa7** [comment]
Just as a follow up - this also causes a crash outside of Dev mode - the faction Levi does not cause a crash however

**Comment by Joeyxxx** [comment]
OK so the standard Levi causes a game crash - thanks.

**Comment by vader111** [comment]
fixed for next version
