### ISSUE TITLE
Minmatar faction capitals buildable without research

### ISSUE THREAD

**Issue by Darthkill** [kabivel/Sins-of-Empires#233]
![faction cap bug 1](https://user-images.githubusercontent.com/33874385/33170646-f2ef9c7c-d040-11e7-8650-8b9fe87c63e6.png)

![faction cap bug 2](https://user-images.githubusercontent.com/33874385/33170690-265209c4-d041-11e7-80e1-8bf0168c8804.png)

Can build minmatar capitals without research

**Comment by Joeyxxx** [comment]
Could we check the other 3 races and raise separate issues please?

**Comment by Darthkill** [comment]
Updated, this no longer seems to occur
