### ISSUE TITLE
Hanger array pictures

### ISSUE THREAD

**Issue by Darthkill** [kabivel/Sins-of-Empires#234]
![hanger arrays picture bug](https://user-images.githubusercontent.com/33874385/33171143-0ca65da2-d043-11e7-8a9c-f71842a9d302.png)

Consistent across minmatar and gallante at least

**Comment by Joeyxxx** [comment]
Are you using the latest version of Ai_revamp branch - I believe this has been fixed?

**Comment by Darthkill** [comment]
Pulled the last branch from last night, last update indicated to be a day ago when I noticed and upgraded

**Comment by Joeyxxx** [comment]
Awesome OK, thanks.
