### ISSUE TITLE
Angel Naglfar Damage

### ISSUE THREAD

**Issue by Darthkill** [kabivel/Sins-of-Empires#242]
Angel Naglfar damage is so low it has to be a bug.
close range guns, 117 tooltip dps, in siege 90 dps.
Thought this might just be UI
Threw 16 of them at an avatar, Didn't get past the shields, Infact, its regening as fast as damage is inflicted.

**Comment by Joeyxxx** [comment]
Can we get a screenshot of this please?

**Comment by kabivel** [comment]
Indeed low dps, fixed now they have arty
