### ISSUE TITLE
Command Titan Doomsday

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#248]
The chain Doomsday is too powerful, it can wipe fleets of Capitals.

Consider increasing the cool down by 3x.
Consider reducing the damage by 30%.

**Comment by TempusLupus** [comment]
It is meant to be a super weapon after all, why nerf it when its doing its
intended purpose

**Comment by Joeyxxx** [comment]
Because it can wipe out an entire fleet of Dreads and FAUX's.

That's not very enjoyable for either player.

**Comment by kabivel** [comment]
reduced the initial damage for T2 DDs of amarr and gallent, Also incresead cooldown in 50%
