### ISSUE TITLE
No interspeters?

### ISSUE THREAD

**Issue by brenene** [kabivel/Sins-of-Empires#44]
I can resherch them but i cant find the build icon?

**Comment by kabivel** [comment]
Intercpetors, are a upgrade to frigates, look there to see if they gain the ability.

**Comment by ScottyErata** [comment]
Brenne this issue has been solved and solution should be committed soon.

**Comment by Joeyxxx** [comment]
Is this fixed?

**Comment by kabivel** [comment]
fixed
