### ISSUE TITLE
Logo hidden when playing as Gallente

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#47]
Select Gallente as race --> Logo is hidden.

This happens if for players and AI.

On the game setup menu:

![image](https://user-images.githubusercontent.com/32372181/30985733-179349a4-a489-11e7-9116-6d59c29053ae.png)

Playing as Gallente:

![image](https://user-images.githubusercontent.com/32372181/30985801-587b476e-a489-11e7-94ac-11d34f3c88a4.png)

**Comment by Malitael** [comment]
Change PSI to Psi
![2017-09-29_16-15-34](https://user-images.githubusercontent.com/28200882/31017667-f36cfd46-a531-11e7-8e2c-6cefe10524fe.png)

**Comment by Joeyxxx** [comment]
I can confirm that this works.

**Comment by kabivel** [comment]
fixed
