### ISSUE TITLE
Optimisation - Freezing

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#48]
The game freezes for 1 second every 10 seconds. Both myself and a friend experience this early to mid-game on wards.

We shall attempt to gather more information and evidence.

**Comment by Joeyxxx** [comment]
Game is running smoothly on the Cache map, which leads me to believe the randomly generated maps may be causing these freezes.

**Comment by Joeyxxx** [comment]
TempusLupus - Today at 3:20 PM
I think the freezing issue could be due to the AI either building or doing something
since it freezes 3 times every 5-10 seconds
for me
and i have 3 ai in my game

**Comment by Joeyxxx** [comment]
Fleet supply will be reduced and tested.

**Comment by Joeyxxx** [comment]
"We've noted that one or two of the particle effects can produce substantial lag. Optimising the warp exit effect wI'll likely help a lot (the big red one). That seems to be a big culprit for frame lag in SOE.
Late game lag is unavoidable to an extent particularly in multilayer. We've found that removing unused entities (like atock ships) from the manifest helps 's lot as they are loaded no matter what if they're in the entity manifest."

"I'd say that the vessels themselves aren't too badly optimised at all and the game still performs well with extensive fleets outside combat.  SOE suports a larger fleet than most sins mods, however and this probably causes some issues when the particles start flting.  With such 's lot of weapons fire from fleets of that size, the ironengine will struggle as it's a 32 bit single threaded app"

**Comment by vader111** [comment]
i will have a crack at the particles when i can

**Comment by vader111** [comment]
[Optimized Particles.zip](https://github.com/kabivel/Sins-of-Empires/files/1355884/Optimized.Particles.zip)

Give these ones a go and let me know though discord

**Comment by Joeyxxx** [comment]
Feedback is extremely positive.

**Comment by Malitael** [comment]
Thank you so much! Now very pleasant to play!

**Comment by Malitael** [comment]
Since last update, again, there were friezes.

**Comment by Joeyxxx** [comment]
Agreed, mid to late game, every 10 seconds, there is a 1 second freeze. This is only vs AI

**Comment by vader111** [comment]
Yeah i gonna be doing more optimizing over the weekend and hopefully try to help with the freezing

**Comment by Joeyxxx** [comment]
Looking good right now - closing the issue.
