### ISSUE TITLE
Trade ports / Planet logistics

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#50]
I would strongly suggest that the number of logistic slots on certain planets is decreased. Building 18 trade ports and upgrading the industrial specialisation provides you with infinite income.

"Scotty Erata - Today at 1:20 PM
I think a good method would be to increase the cost to 4 then decrease the base level of logistics upgrades and let people unlock more through research(edited)
that's 2 birds with 1 stone fix the eco (somewhat) and flesh out the research tree a little
or maybe add research that adds a flat percentage to all logistics slots, idk what the game is capable of"

**Comment by Joeyxxx** [comment]
Logistic slot requirements for Trade Ports and Refinery's has been increased from 2 to 4.

**Comment by kabivel** [comment]
Fixed
