### ISSUE TITLE
Frigates - Cyno

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#51]
Frigates require more antimatter to light a cyno.

![image](https://user-images.githubusercontent.com/32372181/31130852-75f1d630-a850-11e7-81eb-2b632f3a17bb.png)

**Comment by Joeyxxx** [comment]
Working as intended.

kabivel - Today at 3:36 PM
i removed the frigate cyno
kabivel - Today at 3:36 PM
because of the blackops
and frigates could be doing jump bridges
kabivel - Today at 3:36 PM
2 frigates = jump bridge

**Comment by Jer0men** [comment]
If the frigates can no longer do a cyno, can the ability be removed from the hulls and also I believe a text change may be in order on the research page (tbc)

**Comment by kabivel** [comment]
fixed
