### ISSUE TITLE
Cloak bug

### ISSUE THREAD

**Issue by Malitael** [kabivel/Sins-of-Empires#55]
When you activate the cloak it is impossible to turn it off #_#
This is due to the fact that disables the use of abilities.

**Comment by kabivel** [comment]
uauhauhauha

**Comment by DalaryousPT** [comment]
Yeah, this issue appears to be present on every match. Funny about this is that if you get a scout ship cloaked, there is nothing that can uncloak it so you may send it to scout the whole galaxy in safety. :)

**Comment by DalaryousPT** [comment]
This appears to be fixed now. Good job and thank you 👍
