### ISSUE TITLE
Incorrect Icon Tracker 

### ISSUE THREAD

**Issue by Jer0men** [kabivel/Sins-of-Empires#56]
I'll be adding any places where an incorrect icon is used to this thread.

**Comment by Jer0men** [comment]
Caldari Research for Logi upgrade is currently showing a cov-ops icon. 
![unknown](https://user-images.githubusercontent.com/32482382/31221647-3ca85850-a9bc-11e7-8536-eec24b7e7c73.png)

**Comment by Jer0men** [comment]
Same issue for Amarr Logi upgrade

**Comment by kabivel** [comment]
fixed
