### ISSUE TITLE
Suggestion -- Rorqual Ability Start

### ISSUE THREAD

**Issue by robohunterx** [kabivel/Sins-of-Empires#57]
I'm taking a wack that having the rorqs start with the colonize ability, and perhaps a higher range (Making the AI easier to use it) would make the AI a bit quicker on the start of the game since pretty much everything in this game is tied up to expanding.

Yeah I get it that they can build orcas and use them to colonize, but still this gives them the same advantage as a player, without relying on the cheating modes (That gives the AI higher resource incomes) to pad the fact that it's a bit whonky.

**Comment by kabivel** [comment]
change pls test and give a report
