### ISSUE TITLE
Basilisk (T2 Osprey Upgrade) Skin Missing

### ISSUE THREAD

**Issue by robohunterx** [kabivel/Sins-of-Empires#59]
It was like this in the last pull I did, noticed the Basi's skin was missing, replaced with what I'm assuming is the default "No Skin" which is a white.

Might have been corrected, have not tested on current pull.

**Comment by Joeyxxx** [comment]
I believe it's a Chrome effect - however it doesn't look very nice at all.

**Comment by kabivel** [comment]
prints ?

**Comment by vader111** [comment]
will look into it soon
