### ISSUE TITLE
Erebus shield amount lacking a 0?

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#62]
The erebus has 13500 shield, should this be 135000 as per the google sheet:
https://docs.google.com/spreadsheets/d/1fM4SahWOSjbk_QrecXlksRF_SqdWihop8m1AxtTEYVg/edit#gid=0

Gallente_Ship_Capital_Titan_Erebus.entity

The other Erebus file: Gallente_Ship_Titan_Erebus   does have 135000 as shield amount.

**Comment by kabivel** [comment]
fixed
