### ISSUE TITLE
BuffSiegeMode & BuffFighterControlUnit(supercarrier) are debuffs on ROF

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#63]
The abilities 'Siege Mode' and 'Fighter Sup(p)ort Unit' (missing a p there in-game) are currently applying a debuff to ROF instead of a buff. Is this intended?

**Comment by kabivel** [comment]
fixed the (p) sins doesn't support well buff to damage so i applied the rof instead. working as inteded
