### ISSUE TITLE
Ninazu and Megathron repair ability

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#64]
The Ninazu and Megathron both have an ability that states in its description it is a self-repair ability. However both act as remote-repair abilities but lack a range modifier, causing it to default to a very small circle. It also appears that the AI thinks it is a remote-repair ability as my Ninazu with full health tried it use it on a nyx at 50% health with obviously 0 effect. 

![asdd](https://user-images.githubusercontent.com/32543932/31255358-c0b19fce-aa2c-11e7-8c3e-cb7f4fbd7ef8.png)

If it is intended as a self-rep, I'd suggest using buffInstantActionType "ApplyBuffToSelf" in 
"AbilityArmorRepairerCapital"
"AbilityArmorRepairer"
and making a new Buff file to go along with it. But perhaps there is a better way.

This might apply to more abilities, but in any case the Ninazu and Megathron's repair abilities do this.

**Comment by Joeyxxx** [comment]
Now this is very interesting and would explain a lot. Good spot mate.

**Comment by kabivel** [comment]
made this change, please test

**Comment by Malitael** [comment]
Same problem with shield boosters

**Comment by Joeyxxx** [comment]
Shield boosters are not working, as Mal said.

**Comment by vader111** [comment]
fixed for next release
