### ISSUE TITLE
Rorqual still moves during Extractor/Panic ability

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#67]
The ability descriptions for the (Gallente) Rorqual's Extractor buff and Panic abilities imply the Rorqual would be unable to move after it gets activated, however in both cases the Rorqual is unaffected but the targets are affected. In case of Panic the Rorqual also does not become invulnerable but structures do.

**Comment by vader111** [comment]
issue fix for next update
