### ISSUE TITLE
Execuror has same ability twice, shared cooldown

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#68]
As title implies, the Gallente Execuror has 2 Remote repair abilities. However both are "AbilityRemoteArmorRepairerLogiCruiser" causing them to have a shared cooldown.

**Comment by kabivel** [comment]
fixed, now should be idependent

**Comment by Malitael** [comment]
Exactly the same problem and have shield boosters

**Comment by Malitael** [comment]
![2017-10-06_16-57-51](https://user-images.githubusercontent.com/28200882/31281239-85ee474e-aab7-11e7-8182-60b24735dd8f.png)

**Comment by Malitael** [comment]
Augoror too
![2017-10-06_17-42-35](https://user-images.githubusercontent.com/28200882/31283283-d887aea4-aabd-11e7-8dbe-f74a193e4207.png)
