### ISSUE TITLE
Gallente: Icon issues

### ISSUE THREAD

**Issue by BlodBladelicker** [kabivel/Sins-of-Empires#69]
The second common metals extraction upgrade is called 'Gneiss mining' however it has the picture for Hedbergite. 
The fourth common metals extraction upgrade is called 'Bistot mining' like the 3rd common metals upgrade, with a picture of Mercoxit.
The fouth uncommon metals extraction upgrade is called 'Megacyte refining' with a picture of Zydrine.

**Comment by BlodBladelicker** [comment]
![kk](https://user-images.githubusercontent.com/32543932/31263487-d09fa742-aa62-11e7-9bbc-2dd6cc98cf75.png)

Not sure how to refer to that little screen, but the keepstar picture isn't entirely fitting with it causing it to show a little bit of the map below it. 

![kkk](https://user-images.githubusercontent.com/32543932/31263520-0efb32a4-aa63-11e7-8319-c9e4f12fc2cb.png)

The Electronic subsystem for Gallente is missing a 'c' as well as being an icon of a drone rig instead.

**Comment by kabivel** [comment]
electronic subsystem typo fixed
Fortizar picture fixed
