### ISSUE TITLE
Amarr and Minmatar tackle ships unbuildable (User Fix Inside)

### ISSUE THREAD

**Issue by ScottyErata** [kabivel/Sins-of-Empires#72]
Amarr and Minmatar are unable to build their tackle frigates, the Executioner and Slasher respectively. I've attached the player-.entity files which fix this issue.

[GameInfoFixed.zip](https://github.com/kabivel/Sins-of-Empires/files/1362688/GameInfoFixed.zip)

**Comment by kabivel** [comment]
fixed
