### ISSUE TITLE
Trade Port Income OP

### ISSUE THREAD

**Issue by ScottyErata** [kabivel/Sins-of-Empires#73]
Currently there exists a research called "expanded cargoholds" which, when fully researched, increases the income generated by trade hub by ~1500%. This number is far too high. Stacking planets full of trade ports is now a necessary strategy, as with only a few planets a player can generate 200+ credits per second.

I believe this value should be reduced by 50-70%. With this done, the economy still relies on trade hubs, but does not generate a ridiculous amount of cred.

**Comment by Joeyxxx** [comment]
Agreed. This will require some fine tuning via testing, but it's a necessary change.
