### ISSUE TITLE
Marauder MJD ability is autocast by default, AI freaks the fuck out

### ISSUE THREAD

**Issue by ScottyErata** [kabivel/Sins-of-Empires#74]
When builidng a marauder (or its upgradable battleship cousin) the MicroJumpDrive ability has autcast turned on. This means that the AI will automatically jumps the ship around when executing move orders, spreading out the fleet and slowing travel through systems. I will attach a set of ability.entity files which fix this.

**Comment by ScottyErata** [comment]
Here is the fixed file. Extract into /gameinfo

[AbilityMicroJumpDrive.zip](https://github.com/kabivel/Sins-of-Empires/files/1362759/AbilityMicroJumpDrive.zip)

**Comment by Joeyxxx** [comment]
PLEASE @kabivel

**Comment by kabivel** [comment]
Fixed with scotty file
