### ISSUE TITLE
Tiger Obelick! 

### ISSUE THREAD

**Issue by Malitael** [kabivel/Sins-of-Empires#76]
![image](https://user-images.githubusercontent.com/28200882/31283691-fd5763a4-aabe-11e7-9ecb-b33db869f3fd.png)
Rrrr!

**Comment by Malitael** [comment]
And wrong icon 
![image](https://user-images.githubusercontent.com/28200882/31283839-69964e18-aabf-11e7-8d17-922a9e52d75f.png)

**Comment by kabivel** [comment]
we cant change the pictures as the research change level, but the picture in this case is amarr, changed it to gallente iteron.
