### ISSUE TITLE
Propaganda Network icon

### ISSUE THREAD

**Issue by Malitael** [kabivel/Sins-of-Empires#77]
![image](https://user-images.githubusercontent.com/28200882/31287755-0da7ca08-aacb-11e7-9174-42da9fef7e0d.png)

**Comment by smudge202** [comment]
Tested against: 2ce4d9124a34ae40c137afaf7eef7b998aae25ba

To confirm, some races appear to have the correct Icon. Caldari at least, do not:

![propaganda-icon-01](https://user-images.githubusercontent.com/2247869/31901597-cc10dfd8-b819-11e7-9d8d-8e708c522f86.png)

**Comment by BlodBladelicker** [comment]
Gallente also does not have it.
