### ISSUE TITLE
Incursions Active/Inactive Game Settings Text

### ISSUE THREAD

**Issue by Jer0men** [kabivel/Sins-of-Empires#79]
Can the message be changed from 'Sansha Incursions Inactive' to 'Incursions Inactive'

![image](https://user-images.githubusercontent.com/32482382/31306207-e34726fa-ab42-11e7-8e1d-6267b25bb41b.png)

**Comment by vader111** [comment]
noted and will be fixed soon

**Comment by vader111** [comment]
fixed for next update
