### ISSUE TITLE
Tengu balance

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#83]
99% of our multiplayer matches start with "Please, no Tengus or Bomber spam".

This says everything. Tengu's currently cannot be countered and they are very cheap and quick to build.

Please consider:

a) Dramatically increasing the research costs
b) Increasing their build time
c) Increasing their cost

Their damage is probably fine - Scotty is taking a look at the numbers.

**Comment by kabivel** [comment]
Tengu now costs 2x a battleship
Increased in 50% build time
