### ISSUE TITLE
Strange texture

### ISSUE THREAD

**Issue by Malitael** [kabivel/Sins-of-Empires#87]
![image](https://user-images.githubusercontent.com/28200882/31352478-986a15c4-ad37-11e7-919d-a6eaacda5f1d.png)

**Comment by vader111** [comment]
can you point out what exactly you see, as i cannot see anything wrong

**Comment by Malitael** [comment]
Green triangle, zoom in the picture

**Comment by Malitael** [comment]
![image](https://user-images.githubusercontent.com/28200882/31382565-cad21f78-adc0-11e7-9b06-ed434ab20a67.png)

**Comment by Joeyxxx** [comment]
I can't see anything.

**Comment by Malitael** [comment]
So cool to feel special :D

**Comment by vader111** [comment]
fixed with release of new skyboxes
