### ISSUE TITLE
Gallente diplomacy skills

### ISSUE THREAD

**Issue by Joeyxxx** [kabivel/Sins-of-Empires#93]
Gallente diplomacy skills for the envoys require the Ferox envoy BPO.

**Comment by kabivel** [comment]
Wich ones ?

**Comment by Joeyxxx** [comment]
They're on the top row - I can't remember their names. Maniplulation? There are three of them, top row.

**Comment by kabivel** [comment]
I need the exact name of the skill to fix.

**Comment by Joeyxxx** [comment]
OK I'll need to get those this evening.

**Comment by BlodBladelicker** [comment]
Research in question: Mutual Threat
Requires Ferox Envoy BPO instead of Brutix Envoy BPO
The research Mutual Threat is also missing the line to Nanomedicine Outreach.

**Comment by kabivel** [comment]
fixed
